stages:
  - test
  - deploy

test_job:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here
    - echo "Tests passed!"

deploy_to_github:
  stage: deploy
  image: alpine:latest
  only:
    - master
  before_script:
    - apk update && apk add git openssh-client
    - "which ssh-agent || ( apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - rm -rf .git
    - git init
    - git remote add github git@github.com:der-grosse/radio-link-list.git
    - git config user.name "PRIVATE"
    - git config user.email "info@example.com"
    - git add .
    - git commit -m "Deploy to GitHub"
    - git push --set-upstream -f github master
